port = 2121
host = "0.0.0.0"
max_connections = 16777215             # happens to be FFFFFF in base 16
max_passive = 255
exec = "/somewhere/paradise_ftp"
pem = "/certs/server.pem"
key = "/certs/server.key"
